# Generated by Django 5.1.7 on 2025-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_tag_order_customer_order_product_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Out Door', 'Out Door'), ('Indore', 'Indore')], max_length=200),
        ),
    ]
